!ifndef COLORS_IMPORTED
!include ../general/colors.puml
!endif

' Components
' ##################################
skinparam component<<External Container>> {
  FontColor FONT_COLOR
  BorderColor EXTERNAL_BORDER_COLOR
  BackgroundColor EXTERNAL_SYSTEM_BG_COLOR
}

skinparam component<<Internal Container>> {
  FontColor FONT_COLOR
  BorderColor INTERNAL_BORDER_COLOR
  BackgroundColor SYSTEM_BG_COLOR
}
