!ifndef COLORS_IMPORTED
!include ../general/colors.puml
!endif

' Components
' ##################################
  ' PlantUML Rectangle skinning
    'Internal
    skinparam rectangle<<Internal Component>> {
      FontColor COMPONENT_FONT_COLOR
      StereotypeFontColor COMPONENT_FONT_COLOR
      BorderColor INTERNAL_BORDER_COLOR
      BackgroundColor COMPONENT_BG_COLOR
    }

    skinparam rectangle<<Component>> {
      FontColor COMPONENT_FONT_COLOR
      StereotypeFontColor COMPONENT_FONT_COLOR
      BorderColor INTERNAL_BORDER_COLOR
      BackgroundColor COMPONENT_BG_COLOR
    }

    'External
    skinparam rectangle<<External Component>> {
      FontColor EXTERNAL_COMPONENT_FONT_COLOR
      StereotypeFontColor EXTERNAL_COMPONENT_FONT_COLOR
      BorderColor EXTERNAL_BORDER_COLOR
      BackgroundColor EXTERNAL_COMPONENT_BG_COLOR
    }

  ' PlantUML Interface skinning
    'Internal
    skinparam interface<<Internal Component>> {
      BorderColor INTERNAL_BORDER_COLOR
      BackgroundColor COMPONENT_BG_COLOR
    }

    skinparam interface<<Component>> {
      BorderColor INTERNAL_BORDER_COLOR
      BackgroundColor COMPONENT_BG_COLOR
    }

    'External
    skinparam interface<<External Component>> {
      BorderColor EXTERNAL_BORDER_COLOR
      BackgroundColor EXTERNAL_COMPONENT_BG_COLOR
    }

