!ifndef COLORS_IMPORTED
!include ../general/colors.puml
!endif

' Db's
' ##################################
skinparam database<<Internal>> {
  BackgroundColor CONTAINER_BG_COLOR
  BorderColor INTERNAL_BORDER_COLOR
  FontColor CONTAINER_FONT_COLOR
}

skinparam database<<Internal Database>> {
  BackgroundColor CONTAINER_BG_COLOR
  BorderColor INTERNAL_BORDER_COLOR
  FontColor CONTAINER_FONT_COLOR
}

skinparam database<<External>> {
  BackgroundColor EXTERNAL_CONTAINER_BG_COLOR
  BorderColor EXTERNAL_CONTAINER_BORDER_COLOR
  FontColor CONTAINER_FONT_COLOR
}

skinparam database<<External Database>> {
  BackgroundColor EXTERNAL_CONTAINER_BG_COLOR
  BorderColor EXTERNAL_BORDER_COLOR
  FontColor CONTAINER_FONT_COLOR
}
