!include_many ../general/colors.puml

' Expanded
' ##################################
skinparam rectangle<<Expanded Container>> {
  FontColor ATTRIBUTE_AND_EXPANDED_SYSTEM_COLOR
  BorderColor EXTERNAL_BORDER_COLOR
  BackgroundColor EXPENDED_SYSTEM_BACKGROUND_COLOR
  BorderStyle dashed
}

skinparam frame<<Expanded Container>> {
  FontColor ATTRIBUTE_AND_EXPANDED_SYSTEM_COLOR
  BorderColor EXTERNAL_BORDER_COLOR
  BackgroundColor EXPENDED_SYSTEM_BACKGROUND_COLOR
}

skinparam component<<Expanded Container>> {
  FontColor ATTRIBUTE_AND_EXPANDED_SYSTEM_COLOR
  BorderColor EXTERNAL_BORDER_COLOR
  BackgroundColor EXPENDED_SYSTEM_BACKGROUND_COLOR
  BorderStyle dashed
}
