!ifndef COLORS_IMPORTED
!include ../general/colors.puml
!endif

' Expanded
' ##################################
skinparam rectangle<<Expanded>> {
  FontColor ATTRIBUTE_AND_EXPANDED_SYSTEM_COLOR
  BorderColor EXTERNAL_BORDER_COLOR
  BackgroundColor EXPENDED_SYSTEM_BACKGROUND_COLOR
  BorderStyle dashed
}

skinparam frame<<Expanded>> {
  FontColor ATTRIBUTE_AND_EXPANDED_SYSTEM_COLOR
  BorderColor EXTERNAL_BORDER_COLOR
  BackgroundColor EXPENDED_SYSTEM_BACKGROUND_COLOR
  BorderStyle dashed
}

skinparam component<<Expanded>> {
  FontColor ATTRIBUTE_AND_EXPANDED_SYSTEM_COLOR
  BorderColor EXTERNAL_BORDER_COLOR
  BackgroundColor EXPENDED_SYSTEM_BACKGROUND_COLOR
  BorderStyle dashed
}
