!ifndef COLORS_IMPORTED
!include ../general/colors.puml
!endif

' Miscellaneous
' ##################################

  ' PlantUML cloud skinning
    ' External : Clouds are _always_ external
    !ifdef SKIN_CLOUD
    skinparam cloud {
      FontColor SYSTEM_FONT_COLOR
      BorderColor EXTERNAL_SYSTEM_BORDER_COLOR
      BackgroundColor EXTERNAL_SYSTEM_BG_COLOR
    }
    !else
    skinparam cloud<<External>> {
      FontColor SYSTEM_FONT_COLOR
      BorderColor EXTERNAL_SYSTEM_BORDER_COLOR
      BackgroundColor EXTERNAL_SYSTEM_BG_COLOR
    }
    !endif
