!include_many ../general/colors.puml

' Queues
' ##################################
skinparam queue<<Internal>> {
  BackgroundColor SYSTEM_BG_COLOR
  BorderColor INTERNAL_BORDER_COLOR
  FontColor FONT_COLOR
}

skinparam queue<<External>> {
  BackgroundColor EXTERNAL_SYSTEM_BG_COLOR
  BorderColor EXTERNAL_BORDER_COLOR
  FontColor FONT_COLOR
}