!ifndef COLORS_IMPORTED
!include ../general/colors.puml
!endif

!ifdef SKIN_SEQUENCE_DIAGRAM
' Shared
' ##################################

skinparam backgroundColor EXPENDED_SYSTEM_BACKGROUND_COLOR

skinparam sequence {
    ArrowColor SEQUENCE_ITEMS_BORDER_COLOR
    LifeLineBorderColor SEQUENCE_ITEMS_BORDER_COLOR
	LifeLineBackgroundColor SYSTEM_BG_COLOR

    ActorBorderColor SEQUENCE_ITEMS_BORDER_COLOR
    ActorBackgroundColor SYSTEM_BG_COLOR
    ActorFontColor Black
}

skinparam boundary {
      FontColor Black
      BackgroundColor SYSTEM_BG_COLOR
      BorderColor SEQUENCE_ITEMS_BORDER_COLOR
}
skinparam control {
      FontColor Black
      BackgroundColor SYSTEM_BG_COLOR
      BorderColor SEQUENCE_ITEMS_BORDER_COLOR
}
skinparam entity {
      FontColor Black
      BackgroundColor SYSTEM_BG_COLOR
      BorderColor SEQUENCE_ITEMS_BORDER_COLOR
}
skinparam collections {
      FontColor SYSTEM_FONT_COLOR
      BackgroundColor SYSTEM_BG_COLOR
      BorderColor SEQUENCE_ITEMS_BORDER_COLOR
}
skinparam participant {
      FontColor SYSTEM_FONT_COLOR
      BackgroundColor SYSTEM_BG_COLOR
      BorderColor SEQUENCE_ITEMS_BORDER_COLOR
}
skinparam database {
      FontColor Black
      BackgroundColor SYSTEM_BG_COLOR
      BorderColor SEQUENCE_ITEMS_BORDER_COLOR
}

  ' PlantUML Sequence diagram skinning
    ' Internal
    skinparam boundary<<Internal>> {
      BackgroundColor SYSTEM_BG_COLOR
    }

    skinparam control<<Internal>> {
      BackgroundColor SYSTEM_BG_COLOR
    }

    skinparam entity<<Internal>> {
      BackgroundColor SYSTEM_BG_COLOR
    }

    skinparam collections<<Internal>> {
      BackgroundColor SYSTEM_BG_COLOR
    }

    skinparam participant<<Internal>> {
      BackgroundColor SYSTEM_BG_COLOR
    }

    skinparam database<<Internal>> {
      BackgroundColor SYSTEM_BG_COLOR
    }

    ' External
    skinparam boundary<<External>> {
      BackgroundColor EXTERNAL_SYSTEM_BG_COLOR
    }

    skinparam control<<External>> {
      BackgroundColor EXTERNAL_SYSTEM_BG_COLOR
    }

    skinparam entity<<External>> {
      BackgroundColor EXTERNAL_SYSTEM_BG_COLOR
    }

    skinparam collections<<External>> {
      BackgroundColor EXTERNAL_SYSTEM_BG_COLOR
    }

    skinparam participant<<External>> {
      BackgroundColor EXTERNAL_SYSTEM_BG_COLOR
    }

    skinparam database<<External>> {
      BackgroundColor EXTERNAL_SYSTEM_BG_COLOR
    }

!endif