!ifndef COLORS_IMPORTED
!include ../general/colors.puml
!endif

' Systems
' ##################################
skinparam rectangle<<External System>> {
  FontColor FONT_COLOR
  BorderColor EXTERNAL_BORDER_COLOR
  BackgroundColor EXTERNAL_SYSTEM_BG_COLOR
}

skinparam rectangle<<Internal System>> {
  FontColor FONT_COLOR
  BorderColor INTERNAL_BORDER_COLOR
  BackgroundColor SYSTEM_BG_COLOR
}

skinparam rectangle<<External Component>> {
  FontColor FONT_COLOR
  BorderColor EXTERNAL_BORDER_COLOR
  BackgroundColor EXTERNAL_SYSTEM_BG_COLOR
}

skinparam rectangle<<Internal Component>> {
  FontColor FONT_COLOR
  BorderColor INTERNAL_BORDER_COLOR
  BackgroundColor SYSTEM_BG_COLOR
}

