@startuml
!define NO_LEGEND

!include ../../src/c4.puml

rectangle Internal <<Internal Component>>
rectangle External <<External Component>>
interface Internal <<Internal Component>> as IInternal
interface External <<External Component>> as IExternal

Internal          -right-> External
IInternal         -right-> IExternal

'Positioning hints
Internal   -[hidden]down-> IInternal
External   -[hidden]down-> IExternal
@enduml
