@startuml
'!define NO_LEGEND

!include ../../src/c4.puml

component InternalComponent <<Internal Container>>
component ExternalComponent <<External Container>>

rectangle InternalRectangle <<Internal Container>>
rectangle ExternalRectangle <<External Container>>

interface InternalInterface <<Internal Container>>
interface ExternalInterface <<External Container>>

InternalComponent  -right-> ExternalComponent
InternalRectangle  -right-> ExternalRectangle
InternalInterface --right-> ExternalInterface

' Position hints (down can be abbreviated to D etc)
InternalComponent -[hidden]down-> InternalRectangle
InternalRectangle -[hidden]down-> InternalInterface
ExternalRectangle -[hidden]down-> ExternalInterface

@enduml