@startuml
!define NO_LEGEND

!includeurl https://raw.githubusercontent.com/skleanthous/C4-PlantumlSkin/master/build/output/c4.puml

rectangle Internal <<Internal System>>
frame AnotherInternal <<System>>
rectangle External <<External System>>
frame AnotherExternal <<External System>>

Internal -right-> External
Internal -[hidden]down-> AnotherInternal
AnotherInternal -right-> AnotherExternal

@enduml