' Colors
' ##################################
!define PERSON_BG_COLOR #08427B
!define EXTERNAL_PERSON_BG_COLOR #686868
!define SYSTEM_BG_COLOR #1168BD
!define EXTERNAL_SYSTEM_BG_COLOR #999999
!define CONTAINER_BG_COLOR #1168BD
!define EXTERNAL_BORDER_COLOR #707070
!define GENERAL_BORDER_COLOR #707070
!define INTERNAL_BORDER_COLOR #A0A0A0
!define COMPONENT_FONT_COLOR #FFFFFF
!define ATTRIBUTE_AND_EXPANDED_SYSTEM_COLOR #707070
!define EXPENDED_SYSTEM_BACKGROUND_COLOR #F5F5F5