!ifndef COLORS_IMPORTED
!include ../general/colors.puml
!endif

' General params
' ##################################
skinparam {
  shadowing true
  arrowColor GENERAL_BORDER_COLOR
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 150
}
