!ifndef COLORS_IMPORTED
!include ../general/colors.puml
!include ../general/general.puml
!endif

' Legend
' ##################################
!ifndef NO_LEGEND
legend right
|= Color                      |= Type |
|<PERSON_BG_COLOR>            | person |
|<EXTERNAL_PERSON_BG_COLOR>   | external person |
|<SYSTEM_BG_COLOR>            | system |
|<EXTERNAL_SYSTEM_BG_COLOR>   | external system |
|<CONTAINER_BG_COLOR>         | container |
endlegend
!endif

!ifdef NO_LEGEND
!ifndef ENABLE_STEREOTYPES
hide stereotype
!endif
!endif