!include_many colors.puml

' Legend
' ##################################
hide stereotype
legend right
|= Color                      |= Type |
|<PERSON_BG_COLOR>            | person |
|<EXTERNAL_PERSON_BG_COLOR>   | external person |
|<SYSTEM_BG_COLOR>            | system |
|<EXTERNAL_SYSTEM_BG_COLOR>   | external system |
|<CONTAINER_BG_COLOR>         | container |
endlegend