@startuml
!define NO_LEGEND

!include ../src/c4.puml

rectangle InternalSystem <<Internal System>>
rectangle ExternalSystem <<External System>>
rectangle InternalComponent <<Internal Component>>
rectangle ExternalComponent <<External Component>>

InternalSystem -down-> ExternalSystem
ExternalSystem -right-> InternalComponent
InternalComponent -up-> ExternalComponent

@end